# Generated by Django 5.0.4 on 2024-07-04 20:00

from django.db import migrations


def set_new_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')
    items = item_model.objects.all()

    for item in items:
        if item.price <= 10:
            item.rarity = 'Rare'
        elif 11 <= item.price <= 20:
            item.rarity = 'Very Rare'
        elif 21 <= item.price <= 30:
            item.rarity = 'Extremely Rare'
        elif item.price >= 31:
            item.rarity = 'Mega Rare'

    item_model.objects.bulk_update(items, ['rarity'])


def default_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')
    item_model.objects.all().update(rarity='No rarity')


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(set_new_rarity, default_rarity)
    ]
