# Generated by Django 5.0.4 on 2024-07-06 06:39

from django.db import migrations
from datetime import timedelta


def warranty_and_delivery_update(apps, schema_editor):
    Order = apps.get_model('main_app', 'Order')
    updated_orders = []
    deleted_orders = []

    for order in Order.objects.all():
        if order.status == 'Pending':  # Use == for comparison
            order.delivery = order.order_date + timedelta(days=3)
            updated_orders.append(order)
        elif order.status == 'Completed':
            order.warranty = "24 months"
            updated_orders.append(order)
        elif order.status == 'Cancelled':
            deleted_orders.append(order)

    # Bulk update the modified orders
    if updated_orders:
        Order.objects.bulk_update(updated_orders, ['delivery', 'warranty'])

    # Delete the cancelled orders
    for order in deleted_orders:
        order.delete()


def default_warranty_and_delivery(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')
    orders = order_model.objects.all()

    for order in orders:
        if order.status == 'Pending':
            order.delivery = None
        elif order.status == 'Completed':
            order.warranty = order_model._meta.get_field('warranty').default

    order_model.objects.bulk_update(orders, ['delivery', 'warranty'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(warranty_and_delivery_update, default_warranty_and_delivery)
    ]
